spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/merchant_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: merchant-service
