global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8081']
  
  - job_name: 'fraud-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['fraud-service:8082']
  
  - job_name: 'ledger-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ledger-service:8083']
  
  - job_name: 'settlement-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['settlement-service:8084']
  
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8085']
  
  - job_name: 'merchant-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['merchant-service:8086']